version: '3.8'

services:

  redis:
    image: redis:latest
    container_name: redis-secure
    ports:
      - "6379:6379"
    command: ["redis-server"]   # ‚ùó No requirepass
    networks:
      - app-net

  spring-app:
    build: .
    container_name: sample-app
    ports:
      - "4001:4001"
    environment:
      SPRING_REDIS_HOST: redis-secure
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
