version: "3.8"

networks:
  app-net:

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--requirepass", "Demo@123"]
    ports:
      - "6379:6379"
    networks:
      - app-net

  spring-app:
    build: .
    container_name: spring-app
    depends_on:
      - redis
    ports:
      - "4001:4001"
    networks:
      - app-net
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PASSWORD: Demo@123
